options:
  install_sources:
    description: |
      Set install source.
    type: string
    default: ppa:mwhudson/devirt
  custom_registries:
    type: string
    default: "[]"
    description: |
      Registry credentials. Setting this config allows Kubelet to pull images from
      registries where auth is required.

      The value for this config must be a JSON array of credential objects, like this:
        [{"url": "https://my.registry:port", "username": "user", "password": "pass"}]
  disable_gpu:
    type: boolean
    default: false
    description: |
      Disable the autodetection for GPU support.